language: generic
sudo: required
dist: trusty
before_install:
  - sudo aptitude -y install texlive-lang-cjk texlive-xetex texlive-fonts-recommended
install:
  - mkdir -p ${HOME}/texmf/tex/latex
  - (cd ${HOME}/texmf/tex/latex && git clone https://github.com/zr-tex8r/BXjscls.git)
  - mkdir -p ${HOME}/texmf/tex/xelatex
  - (cd ${HOME}/texmf/tex/xelatex && wget http://mirrors.ctan.org/language/japanese/zxjafont/zxjafont.sty)
script:
  - ls
  - pwd
  - make
after_failure:
  - echo "failure"
